server:
  port: 8081
spring:
  jpa:
    show-sql: false
    hibernate:
    ddl-auto: create-drop
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:blogs;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
jwt:
  secret: adJasdjhKKPDFLsdcklkkHdjYriLdjYHTdnjakMnhueyGjFFgasdfDDfsdgfKuIdsd
  expiration: 1800000  # 30 minutes
